/*
************************************
项目名称：Documents解锁会员
软件版本：8.5 time：8.20
特别说明：恢复的时候 商店ID和软件处于同一账户下
下载地址：https://is.gd/EQEQdq
使用声明：⚠️仅供参考，🈲️转载与售卖！

Shadowrocket

[Script]
Documents = type=http-request,pattern=^https:\/\/license\.pdfexpert\.com\/api\/2\.0\/documents\/subscription\/refresh,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Fromboy/JavaScript/Scripts/Documents.js

[MITM]
hostname= %APPEND% license.pdfexpert.com

Quantumultx

[rewrite_local]
^https:\/\/license\.pdfexpert\.com\/api\/2\.0\/documents\/subscription\/refresh url script-request-body https://raw.githubusercontent.com/Fromboy/JavaScript/Scripts/Documents.js

[mitm]
hostname = license.pdfexpert.com

**************************************
*/


[Script]
Documents = type=http-request,pattern=^https:\/\/license\.pdfexpert\.com\/api\/2\.0\/documents\/subscription\/refresh,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Fromboy/JavaScript/Scripts/Documents.js

[MITM]
hostname= %APPEND% license.pdfexpert.com