#!name=Grow.module

#!desc=Grow解锁会员

#!homepage=https://yfamily.vercel.app

#!@1.12.1 下载地址： https://www.123pan.com/s/stMmjv-U4dE.html

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/grow.png

[Script]
GrowForeverVipCrack = type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Fromboy/JavaScript/Scripts/GrowForeverVipCrack.js

[MITM]
hostname= %APPEND% api.revenuecat.com
