#!name=Grow

#!desc=Grow解锁会员

#!homepage=https://yfamily.vercel.app

#!author=109954496

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/grow.png

[Script]

Grow=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/(\$RCAnonymousID\%)?(\w)+$ ,requires-body=1,script-path=https://raw.githubusercontent.com/Fromboy/JavaScript/Scripts/Grow.js

Grow1=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/receipts$ ,requires-body=1,script-path=https://raw.githubusercontent.com/Fromboy/JavaScript/Scripts/Grow.js

[MITM]

hostname= %APPEND% api.revenuecat.com